 $$A = \left [\begin {array} {ccc} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end {array} \right], B = \left [\begin {array} {ccc} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end {array} \right]$$

In [1]:
import numpy as np

## [Problem 1] Manually calculate the matrix product
Solve the matrix product of A and B by hand.

Please explain the calculation process using markdown text.

In [2]:
a_ndarray = np.array([[-1, 2, 3],
                      [4, -5, 6],
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]])

print('A = \n{}'.format(a_ndarray))
print('B = \n{}'.format(b_ndarray))

A = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
B = 
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [3]:
c_ndarray = np.zeros((3,3))
print('C = \n{}'.format(c_ndarray))

for i in range(len(a_ndarray)):
   for j in range(len(b_ndarray[0])):
       for k in range(len(b_ndarray)):
           c_ndarray[i][j] += a_ndarray[i][k] * b_ndarray[k][j]

print('C = AB = \n{}'.format(c_ndarray))

C = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
C = AB = 
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


> In order to multiply two matrices, matrix A$(n \times m)$'s no. columns need to be equal to matrix B$(m \times l)$'s no. rows. So matrix C need to be a $(n \times l)$ matrix

First we use `np.zeros()` to create a $(n \times l)$ matrix in order to store our result.

Then we iterate through each row of matrix A, then each column and row of matrix B to have the multiplying formula.

For example:
$$c_{12} = a_{11}b_{12} + a_{12}b_{22}\\
c_{33} = a_{31}b_{13} + a_{32}b_{23}$$

## [Problem 2] Calculation by NumPy function
The matrix product is of *NumPy* `np.matmul()` and `np.dot()`, or `@` can be easily calculated by using the operator.

Use these to calculate the matrix product.

In [4]:
c_ndarray = np.zeros((3,3))
print('C = \n{}'.format(c_ndarray))
c_ndarray = np.dot(a_ndarray,b_ndarray)
print('\nnp.dot()\nC = AB = \n{}'.format(c_ndarray))
# print(a_ndarray.dot(b_ndarray))

C = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.dot()
C = AB = 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
c_ndarray = np.zeros((3,3))
print('C = \n{}'.format(c_ndarray))
c_ndarray = np.matmul(a_ndarray,b_ndarray)
print('\nnp.matmul()\nC = AB = \n{}'.format(c_ndarray))

C = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.matmul()
C = AB = 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [6]:
c_ndarray = np.zeros((3,3))
print('C = \n{}'.format(c_ndarray))
c_ndarray = (a_ndarray @ b_ndarray)
print('\nC = A @ B = \n{}'.format(c_ndarray))

C = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

C = A @ B = 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## [Problem 3] Implement the calculation of a certain element

In [39]:
c_ndarray = np.zeros(1)
# c_ndarray

for k in range(len(b_ndarray)):
    c_ndarray += a_ndarray[0][k] * b_ndarray[k][0]

c_ndarray

array([6.])

## [Problem 4] Creation of a function that performs matrix multiplication
Extend the code in Problem 3 to complete the matrix product scratch implementation. Make it a function that takes matrices A and B as arguments and returns a matrix product.

In [20]:
def mul_matrices(a_ndarray,b_ndarray):
    c_ndarray = np.zeros((3,3))
    # print('C = \n{}'.format(c_ndarray))

    for i in range(len(a_ndarray)):
       for j in range(len(b_ndarray[0])):
           for k in range(len(b_ndarray)):
               c_ndarray[i][j] += a_ndarray[i][k] * b_ndarray[k][j]

    return c_ndarray

In [21]:
mul_matrices(a_ndarray,b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## [Problem 5] Judging the input for which the calculation is not defined
The function created in Problem 4 may work even if you enter this array of D and E depending on the implementation method. In this case, improper calculation will be performed. 

Also, even if an error occurs in the middle, a message is displayed that makes it difficult to directly understand why the error occurred.

In [10]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [26]:
def judge_mul_matrices(a_ndarray,b_ndarray):
    if len(a_ndarray[0]) == len(b_ndarray):
        return mul_matrices(a_ndarray,b_ndarray)
    else:
        print("Error! The number of columns in Matrix 1 is not equal to the number of rows in Matrix 2!")

In [27]:
judge_mul_matrices(d_ndarray,e_ndarray)

Error! The number of columns in Matrix 1 is not equal to the number of rows in Matrix 2!


## [Problem 6] Transpose
By transposing one of the matrices, the matrix product can be calculated.

`np.transpose()` or `.T` Transpose using andattributes to calculate the matrix product.

In [36]:
d_ndarray = d_ndarray.T
judge_mul_matrices(d_ndarray,e_ndarray)

array([[ 33., -28.,   9.],
       [-48.,  41.,  -6.],
       [  9.,  -6.,  45.]])